"""T4.3 — HTML session 导出。

自包含（inline CSS，无外部资源依赖），可被任意浏览器离线打开。

设计要点：
- 委托 ``utils.html_utils`` 处理 XSS escape / URL 白名单 / 三色 callout / 文档组装
  （Sprint 9.1 T9.1.1：HTML 工具从 session export 抽出到共享 utils）
- 入口：``render_html(tree) -> str`` 与 ``export_html(tree, path) -> Path``
"""

from __future__ import annotations

import html
from pathlib import Path

from claude_autosar.core.log.changelog import Change, extract_changes
from claude_autosar.core.session.store import SessionEntry
from claude_autosar.core.session.tree import SessionTree
from claude_autosar.utils.html_utils import (
    render_callout,
    render_html_doc,
    render_inline_md,
)

# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------


def render_html(tree: SessionTree) -> str:
    """把 SessionTree 渲染为完整 HTML 字符串。"""
    body_parts: list[str] = []
    body_parts.extend(_render_header(tree))
    body_parts.extend(_render_entries(tree))
    body_parts.extend(_render_changes(tree))
    return render_html_doc(
        title=f"AutoC Session {tree.session.id}",
        body_parts=body_parts,
        footer='<div class="footer">Generated by AutoC</div>',
    )


def export_html(tree: SessionTree, output_path: Path | str) -> Path:
    """渲染 HTML 并写到文件，返回绝对路径。"""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_html(tree), encoding="utf-8")
    return out.resolve()


# ---------------------------------------------------------------------------
# 段落
# ---------------------------------------------------------------------------


def _render_header(tree: SessionTree) -> list[str]:
    s = tree.session
    title_html = f" — {html.escape(s.title)}" if s.title else ""
    return [
        f"<h1>AutoC Session {html.escape(s.id)}{title_html}</h1>",
        '<div class="meta">',
        f"started_at: {html.escape(s.started_at or '(empty)')}",
        f" &middot; entries: {len(s.entries)}",
        "</div>",
    ]


def _render_entries(tree: SessionTree) -> list[str]:
    out = ["<h2>Conversation</h2>"]
    for entry in tree.session.entries:
        out.append(_render_entry(entry))
    return out


def _render_entry(entry: SessionEntry) -> str:
    kind = html.escape(entry.kind)
    ts = html.escape(entry.timestamp)
    cls = f"entry {kind}"
    # content 用 inline md 渲染（先 escape 后替换为受控 HTML）
    content_html = render_inline_md(entry.content)
    body = f'<div class="content">{content_html}</div>'
    if entry.tool_name:
        # 工具调用：显示为改参 callout（如果 tool_args 是 bsw_write 风格）
        body += _render_tool_args(entry)
    return (
        f'<div class="{cls}">'
        f'<div class="ts">[{ts}] {kind}'
        f'{f" ({html.escape(entry.tool_name)})" if entry.tool_name else ""}'
        f"</div>"
        f"{body}"
        f"</div>"
    )


def _render_tool_args(entry: SessionEntry) -> str:
    """根据 tool_args 渲染 callout（仅 bsw_write 风格）。"""
    if entry.tool_name != "bsw_write":
        return ""
    args = entry.tool_args or {}
    op = str(args.get("op", "modify"))
    module = str(args.get("module", ""))
    path = str(args.get("path", ""))
    value_repr = repr(args.get("value"))
    old_value = args.get("old_value")
    url = f"{module}/{path}" if module else path
    detail = ""
    if op == "modify" and old_value is not None:
        detail = (
            f'<span class="ts">{html.escape(repr(old_value))} '
            f"→ {html.escape(value_repr)}</span>"
        )
    elif op == "add":
        detail = f'<span class="ts">= {html.escape(value_repr)}</span>'
    elif op == "delete":
        detail = f'<span class="ts">(was: {html.escape(repr(old_value))})</span>'
    return render_callout(op=op, label=f"{op.upper()} {url}", detail=detail)


def _render_changes(tree: SessionTree) -> list[str]:
    changes: list[Change] = extract_changes(tree)
    if not changes:
        return []
    # 复用 core.log.changelog 的渲染（避免重复实现）
    from claude_autosar.core.log.changelog import render_by_url, render_timeline

    return [
        '<div class="changes-section">',
        "<h2>Changes Timeline</h2>",
        f"<pre>{html.escape(render_timeline(changes))}</pre>",
        "<h2>Changes By URL</h2>",
        f"<pre>{html.escape(render_by_url(changes))}</pre>",
        "</div>",
    ]
